server:
  port: 8989

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: authenticationMicroservice
          uri: lb://AUTHENTICATION-MICROSERVICE
          predicate:
          - path: /authentication/**
         filters:
          - name: CircutBreaker
          - args:
              name: authenticationMicroservice
              fallbackuri: forward:/authenticationFallBack
          - id: biddingService
            uri: lb://BIDDING-MICROSERVICE
            predicate:
          - path: /bidding/**
         filters:
         - name: CircutBreaker
         - args:
            name: productService
            fallbackuri: forward:/productFallBack
         - id:
            uri: lb://BIDDING-MICROSERVICE
            predicate:
              - path: /bidding/**
            filters:
              - name: CircutBreaker
              - args:
                  name: biddingService
                  fallbackuri: forward:/biddingFallBack
         - id: productService
             uri: lb://BIDDING-MICROSERVICE
             predicate:
               - path: /bidding/**
             filters:
               - name: CircutBreaker
               - args:
                   name: biddingService
                   fallbackuri: forward:/biddingFallBack
  eureka:
    client:
      register-with-eureka: true
      service-url:
        defaultZone: http://localhost:8762/eureka/
  instance:
    hostname: localhost



  hystrix:
    command:
      fallbackcmd:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 4000


  management:
    endpoints:
      web:
        exposure:
          include: hystrix.stream




